172 removed add button
Banyan-Labs/CiannaLighting pull request #205
Opened 2023-02-22 17:40 UTC by jmclain-banyan

😆  added the remove buttons
![image](https://user-images.githubusercontent.com/83558840/220710690-3e23b77b-d0a5-4f45-82c8-f265622dd514.png)

2023-02-22 19:25 UTC, owen-the-terrible requested changes
If you tested them out and they're working the right way then cool but will you give those a looksie?

2023-02-22 19:25 UTC, owen-the-terrible commented on client/src/components/Inventory/Inventory.tsx
> +                                        removeItem(e, 'exteriorFinish')
Does this line need `designStyle`  included in that removeItem function?

2023-02-22 19:25 UTC, owen-the-terrible commented on client/src/components/Inventory/Inventory.tsx
> +                                        removeItem(e, 'exteriorFinish')
Also does this one need 'usePackages' included in the removeItem function?

2023-02-22 19:38 UTC, jmclain-banyan commented on client/src/components/Inventory/Inventory.tsx
> +                                        removeItem(e, 'exteriorFinish')
my bad, good catch.

2023-02-22 19:38 UTC, jmclain-banyan commented on client/src/components/Inventory/Inventory.tsx
> +                                        removeItem(e, 'exteriorFinish')
another one, you're right

2023-02-23 16:41 UTC, owen-the-terrible approved these changes
Thanks bruh

2023-02-23 19:30 UTC, merged